[vault]
# Network
protocl = "https"
status_path = "/v1/sys/health?standbyok=true"
unseal_path = "/v1/sys/unseal"
# Settings
unseal_key_count = 3
# Interval in ms
seal_check_interval = 100

[workers]
# The amout of workers to make
status_check = 3
unseal = 3
logging = 1

[servers]
    # Server instances in the cluster
    [[instance]]
    domain = "vault-0.cluster.local"

    [[instance]]
    domain = "vault-1.cluster.local"

    [[instance]]
    domain = "vault-2.cluster.local"
