[vault]
# Network
protocol = "http"
status_path = "v1/sys/health?standbyok=true"
unseal_path = "v1/sys/unseal"
# Settings
unseal_key_count = 3
# Interval in ms
seal_check_interval = 100

[workers]
# The amout of workers to make
status_check = 3
unseal = 3
logging = 1

[[server]]
domain = "vault-0:8200"

[[server]]
domain = "vault-1:8200"
